### ISSUE TITLE
variant page misfeatures

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/pheweb#280]
- Consequence (missense,intergenic etc...) of the variant is missing

- Number of homozygotes is missing
- gnomAD AF comparison should come from our new annotation file
- It says p-values are shown on a log-log scale but they are not (should be though since variants with a good association are difficult to navigate in the volcano now)
- Table header says beta (se) but there’s no SE
-Table header says beta (se) but there’s no SE (i.e. standard error). Either add se to the table or remove "(se)" from the header.
- The text is smaller than usually in the web. Trouble reading with a small display resolution
- p-values smaller than 1e-10 should be  shown on a log-log scale as previously.
-

**Comment by juhis** [comment]
There is a new annotation file `gs://r10-data/annotation/R10_annotated_variants_v2.gz` - the older ones are broken - maybe this has to do with the variant page annotations not showing up
