### ISSUE TITLE
On the gene page in "All loss of function and missense variants" table, it says OR but reports beta

### ISSUE THREAD

**Issue by juhis** [FINNGEN/pheweb#383]
If we want to show odds ratio (OR), need to take OR=exp(beta). But for quantitative traits (BMI, height, weight) there is no OR so showing beta for all traits would be simple and consistent across binary and quantitative traits

**Comment by Fedja** [comment]
<img width="1348" alt="image" src="https://github.com/FINNGEN/pheweb/assets/2276082/b751d08b-8245-43b5-8ab4-d7447055342c">

**Comment by Fedja** [comment]
@anastasia-shch if you can switch text to beta

**Comment by anastasia-shch** [comment]
Added as a part of https://github.com/FINNGEN/pheweb/commit/8740206845c5c926495d22eca14a3b02fc19a4dd
