### ISSUE TITLE
create public metaresults browser

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/pheweb#390]
We want to show FinnGen release 9 metaresults for FG + UKBB. Can you @juhaa point to the imported data if still exists?
URL should be
https://public-metaresults-est-ukbb.finngen.fi/

**Comment by juhaa** [comment]
Just to clarify, 2-way or 3-way meta results @Fedja ? In any case, the R9 meta imported data is at production-meta-instance-nfs:/data/nfs/pheweb/r9*
