### ISSUE TITLE
Track size in chrome browser for the manhattan hits

### ISSUE THREAD

**Issue by aelliott08** [FINNGEN/pheweb#41]
When using a chrome browser to view pheweb hits from the manhattan plot, the spacing of the tracks is a little funny. Particularly for the "GWAS Catalog + UKBB" track.  I have to make the track really tall to be able to click on the top diamond of the track.   See link below. 

http://results.finngen.fi/region/E4_DM2_STRICT/X:153434467-153834467

**Comment by juhis** [comment]
Fixed by #57
