### ISSUE TITLE
add "table of contents" to gene page

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/pheweb#426]
In gene page, add table of contents after the gene description and link.

Each link should be clickable and take user to the relevant section. 

Table of contents and reorder of the sections. 

"Disease associations within gene region"
"Coding variant associations"
"Protein truncating variant burden associations"
"pQTL and colocalizations"
"Drugs targeting the gene"

**Comment by anastasia-shch** [comment]
This feature was implemented as part of the PR#441.
