### ISSUE TITLE
gene page switch thetext OR to beta in coding variant table

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/pheweb#437]
<img width="1375" alt="image" src="https://github.com/FINNGEN/pheweb/assets/2276082/506ef50b-d8f1-480b-8f7a-c5a3d550a831">

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1422524734) by [Unito](https://www.unito.io)

**Comment by anastasia-shch** [comment]
This was implemented @Fedja .
