### ISSUE TITLE
Links from variants in conditioned or finemapped plots do not work

### ISSUE THREAD

**Issue by Lipastomies** [FINNGEN/pheweb#45]
__What:__
Links from locuszoom variants in conditioned/finemapped plots lead to http://results.finngen.fi/variant/---, which is different from the link from the FINNGEN plot and does not show any variant information.
__How to replicate:__
Go to a locuszoom region with conditioned/finemapped variants, e.g. http://results.finngen.fi/region/THROMBOCYTAEMIA/9:4873770-5273770
Click on e.g. 9:5126913_G/A in the conditioned plot, or 9:5073770_G/T in the finemapping plot (or any other variant).

**Comment by juhis** [comment]
Fixed #48
