### ISSUE TITLE
bed file not found

### ISSUE THREAD

**Issue by majorseitan** [FINNGEN/pheweb#451]
Master seems to be looking for the bed file in the wrong location
For r12 I am getting the error:
No such file or directory: '/mnt/nfs/pheweb/r12/release/cache/genes-b38-v39.bed'
Where as the available bed file is 'genes-b38-v37.bed'

image:
eu.gcr.io/phewas-development/pheweb:ci-6fa43a03ff614e23a556aa6ededb95ae852d7b29

**Comment by anastasia-shch** [comment]
@majorseitan This is due to the recent update related to the gene version in the code: v37 -> v39. I added fixed bed file to the nfs -  do you still get the error?
