### ISSUE TITLE
coding browser anomaly

### ISSUE THREAD

**Issue by mjdaly67** [FINNGEN/pheweb#463]
When I search for TRAPPC10 by entering it in the 'show all results for a gene' box, it returns 

"PARSING ERROR"

and nothing else...

The gene looks perfectly normal in https://results.finngen.fi/gene/TRAPPC10 and does have missense variants...

<img width="418" alt="Screenshot 2024-02-17 at 1 55 30 PM" src="https://github.com/FINNGEN/pheweb/assets/11999331/d5c2b356-9149-4d72-ae12-f41469c3df3f">

**Comment by mjdaly67** [comment]
actually it seems the whole feature is broken - but seemingly in the last half day since I was using it without issue yesterday

**Comment by anastasia-shch** [comment]
It seems there are NaNs in the data extracted from the db and they are not parsed correctly - we get "not valid JSON" error, will fix that.

**Comment by mjdaly67** [comment]
Thanks Anastasia!!
