### ISSUE TITLE
Risteys button link bug on phenotype page

### ISSUE THREAD

**Issue by vincent-octo** [FINNGEN/pheweb#47]
Looks like there is a small templating issue with the button link to Risteys on the phenotype page.

For example on https://results.finngen.fi/pheno/E4_DM2 the Risteys button links to https://risteys.finngen.fi/phenocode/%7B%7B%20this.state.pheno.phenocode.replace('_EXALLC',%20'').replace('_EXMORE',%20'')%20%7D%7D

**Comment by juhis** [comment]
Fixed #48
