### ISSUE TITLE
Error message on home page if not logged in

### ISSUE THREAD

**Issue by vincent-octo** [FINNGEN/pheweb#53]
If a user is not already logged in, then an error message is displayed when reaching PheWeb home page.

## Steps to reproduce

1. If already logged-in: log out of PheWeb or open PheWeb in a browser private window.

2. Go to results.finngen.fi

## Expected
Have a button or link or login form to log into PheWeb.

## Actual
The following error message:
![image](https://user-images.githubusercontent.com/4919840/74812567-68b2b580-52fc-11ea-8c0c-57a082cda1b0.png)

## Notes
It is still possible for users to login by clicking "ok" on this error message and then clicking one of the header links.

**Comment by juhis** [comment]
Closed by #48
