### ISSUE TITLE
Add open targets link to variant view

### ISSUE THREAD

**Issue by sinarueeger** [FINNGEN/pheweb#60]
The [variant view](http://results.finngen.fi/variant/11-116778201-G-C) links the variant to UCSC , GWAS Catalog , dbSNP, but not open targets (like the [gene view](http://results.finngen.fi/gene/ZPR1) does). 

Variant view in open targets has the following url: 
https://genetics.opentargets.org/variant/11_116778201_G_C

## Checks
Variant [rs964184/11-116778201-G-C](http://results.finngen.fi/variant/11-116778201-G-C) has the link to https://genetics.opentargets.org/variant/11_116778201_G_C.

**Comment by juhis** [comment]
Fixed
