### ISSUE TITLE
Is there a way to get the datafiles used in finngen pheweb for offline use?

### ISSUE THREAD

**Issue by thondeboer** [FINNGEN/pheweb#71]
We would like to utilize the FINNGEN version of the PHEWEB server but there is a reference in the config files to a large number of files that are not readily available, such a:

![image](https://user-images.githubusercontent.com/3422829/94072889-5ecdc500-fdab-11ea-891b-fb2355f66f5f.png)

Are those files available somewhere or are they perhaps even automatically downloaded like so many other files in pheweb or is this just an example of what this pheweb server can be used for and it is up to me to construct all those files? For some of the files are not obvious what the format and content should be so this is somewhat tricky...

**Comment by juhis** [comment]
Hi, these are largely FinnGen specific and we don't currently have the bandwidth to provide an out-of-the-box installation unfortunately
